### ISSUE TITLE
Go-live process notes

### ISSUE THREAD

**Issue by benlk** [INN/umbrella-ipbs#52]
- [ ] set up homepage as described in https://github.com/INN/umbrella-ipbs/pull/51

**Comment by benlk** [comment]
- [ ] calendar configuration from https://github.com/INN/umbrella-ipbs/pull/68
- [ ] footer widget and menu configurations https://github.com/INN/umbrella-ipbs/pull/54
- [ ] header and menu configurations https://github.com/INN/umbrella-ipbs/pull/53

**Comment by joshdarby** [comment]
- [ ] homepage our impact section configuration #70 
- [ ] homepage events calendar plugin config from #68

**Comment by joshdarby** [comment]
- [ ] job board config detailed in #75 
- [ ] homepage video config in #78
